//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities1 : DbContext
    {
        public CMSEntities1()
            : base("name=CMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblLogin> tblLogin { get; set; }
        public DbSet<tblNotification> tblNotification { get; set; }
        public DbSet<tblShipping> tblShipping { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
    }
}
