//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipping
    {
        public string shippingID { get; set; }
        public string userID { get; set; }
        public Nullable<System.DateTime> dateDepart { get; set; }
        public string itemCategory { get; set; }
        public Nullable<decimal> itemWeight { get; set; }
        public string locationFrom { get; set; }
        public string locationTo { get; set; }
        public string dateArrived { get; set; }
        public string status { get; set; }
    }
}
